-- 更新订单中过了时间状态为失效

DROP PROCEDURE IF EXISTS `TRV_ORDER_UPDATE_ORDERINFO`;

DELIMITER $$
CREATE PROCEDURE `TRV_ORDER_UPDATE_ORDERINFO`(IN ORDER_STATUS VARCHAR(3))
BEGIN 
	UPDATE `TRV_SPOT_ORDER` T SET T.ORDER_STATUS = ORDER_STATUS WHERE T.TIME_EXPIRE >= FROM_UNIXTIME(UNIX_TIMESTAMP(),"%Y%m%d%H%i%s");
	COMMIT;
END$$
DELIMITER;

-- 每分钟执行下,更新订单中过了失效时间的状态
CREATE EVENT IF NOT EXISTS TRV_ORDER_UPDATE_ORDERINFO_SCHEDULER
ON SCHEDULE EVERY 1 minute
on completion preserve
do call TRV_ORDER_UPDATE_ORDERINFO('4');

